export const DEFAULT_VOLUME = 100;
export const MAX_VOLUME = 200;
export const SETTINGS_KEY = "settings";

export const DEFAULT_SETTINGS = Object.freeze({
  masterVolume: DEFAULT_VOLUME,
  siteVolumes: {},
});

export const MESSAGE = Object.freeze({
  GET_AUDIO_STATE: "GET_AUDIO_STATE",
  SET_TAB_VOLUME: "SET_TAB_VOLUME",
  SET_TAB_MUTED: "SET_TAB_MUTED",
  RESET_TAB: "RESET_TAB",
  RELEASE_TAB: "RELEASE_TAB",
  SET_MASTER_VOLUME: "SET_MASTER_VOLUME",
  RESET_ALL: "RESET_ALL",
  RELEASE_ALL: "RELEASE_ALL",
  AUDIO_STATE_CHANGED: "AUDIO_STATE_CHANGED",
  OFFSCREEN_GET_STATE: "OFFSCREEN_GET_STATE",
  OFFSCREEN_START_TAB: "OFFSCREEN_START_TAB",
  OFFSCREEN_SET_TAB: "OFFSCREEN_SET_TAB",
  OFFSCREEN_STOP_TAB: "OFFSCREEN_STOP_TAB",
  OFFSCREEN_SET_MASTER: "OFFSCREEN_SET_MASTER",
  OFFSCREEN_RESET_ALL: "OFFSCREEN_RESET_ALL",
  OFFSCREEN_STOP_ALL: "OFFSCREEN_STOP_ALL",
});
